version: '3.7'

services:
  frontend:
    container_name: cider-log-frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - web
    ports:
      - 8080:80
  api:
    container_name: cider-log-api
    environment:
      PORT: 5000
      FLASK_DEBUG:
      FLASK_ENV:
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    networks:
      - web
  db:
    image: postgres:17.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data:

networks:
  web:
    external: true