version: '3.7'

services:
  frontend:
    container_name: cider-log-frontend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      web:
    ports:
      - 8080:80
  api:
    container_name: cider-log-api
    hostname: cider-api
    environment:
      PORT: 5000
      FLASK_DEBUG:
      FLASK_ENV:
      FLASK_RUN_PORT: 5000
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DB_URI: postgresql://postgres@flask_db:5432/postgres
    build:
      context: .
      dockerfile: Dockerfile.backend
    networks:
      web:
  db:
    image: postgres:17.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    expose:
      - 5432
    profiles:
      - debug
      - development
    networks:
      web:
        aliases:
          - flask_db
          - postgres

volumes:
  postgres_data:

networks:
  web:
    external: true