[project]
name = "cider-adventure-log"
version = "0.1.0"
description = "Application to track Ciders that have been tested and review how good they were"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask~=3.1",
    "flask-cors~=5.0.1",
    "flask-login>=0.6.3",
    "flask-migrate~=4.1",
    "flask-pyoidc~=3.14.3",
    "flask-sqlalchemy~=3.1",
    "gunicorn>=26.0.0",
    "openpyxl>=3.1.5",
    "pillow~=11.0",
    "psycopg2-binary~=2.9.11",
    "pyzbar~=0.1.9",
]

[dependency-groups]
dev = [
    "ipython",
]
