apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cask-and-cup-secrets
  namespace: cask-and-cup
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: cask-and-cup-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secretKey }}"
        FLASK_DB_URI: "postgresql://{{ .dbUsername }}:{{ .dbPassword }}@postgres-cluster-rw.postgres.svc.cluster.local:5432/cask_and_cup"
        AUTHENTIK_CLIENT_ID: "{{ .oidcClientId }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .oidcClientSecret }}"
  data:
    - secretKey: secretKey
      remoteRef:
        key: cask-and-cup-secret-key/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: dbUsername
      remoteRef:
        key: cask_and_cup-db/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: dbPassword
      remoteRef:
        key: cask_and_cup-db/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: oidcClientId
      remoteRef:
        key: cask-and-cup-oauth/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: oidcClientSecret
      remoteRef:
        key: cask-and-cup-oauth/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
