"""Add tasting_notes to coffee_details

Revision ID: 0284c7492f4e
Revises: f452bc24ee49
Create Date: 2026-08-09 13:29:07.460276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0284c7492f4e'
down_revision = 'f452bc24ee49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tasting_notes', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffee_details', schema=None) as batch_op:
        batch_op.drop_column('tasting_notes')

    # ### end Alembic commands ###
