"""initial schema: beverage types, barcode, user, rating

Revision ID: f452bc24ee49
Revises: 
Create Date: 2026-07-31 19:23:26.556184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f452bc24ee49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('authentik_sub', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('authentik_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_table('barcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beverage_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cider_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beverage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffee_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('roast_level', sa.String(), nullable=True),
    sa.Column('process', sa.String(), nullable=True),
    sa.Column('varietal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beverage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beverage_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('purchase_location', sa.String(), nullable=True),
    sa.Column('consumption_location', sa.String(), nullable=True),
    sa.Column('consumption_method', sa.String(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beverage_id'], ['beverage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whiskey_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['beverage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whiskey_details')
    op.drop_table('rating')
    op.drop_table('coffee_details')
    op.drop_table('cider_details')
    op.drop_table('barcode')
    op.drop_table('user')
    op.drop_table('beverage')
    # ### end Alembic commands ###
